services:
  # 1. The Cache Layer
  redis:
    image: redis:alpine
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes # Enable data persistence

  # 2. The Java Backend
  backend:
    build: ./backend
    container_name: rate-limiter-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_DATA_REDIS_HOST=redis # Connects to the service name above

  # 3. The Angular Frontend
  frontend:
    build: ./frontend
    container_name: security-dashboard-ui
    ports:
      - "4200:80" # Maps container port 80 to your machine 4200
    depends_on:
      - backend

  # 4. Prometheus (Metrics Collection)
  prometheus:
    image: prom/prometheus:latest
    container_name: security-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus # This saves your graph history
    ports:
      - "9090:9090"
    depends_on:
      - backend

  # 5. Grafana (Metrics Dashboard)
  grafana:
    image: grafana/grafana:latest
    container_name: security-grafana
    volumes:
      - grafana-data:/var/lib/grafana # This saves your dashboard settings
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  
  # Define the volumes at the bottom of the file
volumes:
  prometheus-data:
  grafana-data: