global:
  scrape_interval: 5s # Scrape every 5 seconds for real-time graphs
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-rate-limiter'
    metrics_path: '/actuator/prometheus' # The endpoint we enabled in properties
    static_configs:
      - targets: ['rate-limiter-api:8080'] # Using the container name here!